version: "3"

volumes:
  socket-volume:
  frontend-public-volume:

services:
  mongo:
    image: mongo:2.6.4
    ports:
      - 27017:27017

  nginx:
    image: jnorwood/stupidchess-nginx:current
    entrypoint:
      - nginx
      - -c
      - /etc/nginx/local/nginx.conf
      - -g
      - daemon off;
    volumes:
      - ../etc/nginx:/etc/nginx/local:ro
      - socket-volume:/tmp/sockets
      - frontend-public-volume:/var/lib/johnmalcolmnorwood/stupidchess/dist:ro
    ports:
      - 80:80

  uwsgi:
    image: jnorwood/stupidchess-uwsgi:current
    entrypoint:
      - uwsgi
      - --ini
      - /etc/uwsgi/uwsgi.ini:local
    environment:
      - JCONFIGURE_ACTIVE_PROFILES=LCL
      - JCONFIGURE_CONFIG_DIRECTORIES=/var/lib/johnmalcolmnorwood/stupidchess/server/config
    volumes:
      - ../server/packages/auth/src/com/johnmalcolmnorwood/auth:/usr/local/lib/python3.6/site-packages/com/johnmalcolmnorwood/auth:ro
      - ../server/packages/stupidchess/src/com/johnmalcolmnorwood/stupidchess:/usr/local/lib/python3.6/site-packages/com/johnmalcolmnorwood/stupidchess:ro
      - ../server/config:/var/lib/johnmalcolmnorwood/stupidchess/server/config:ro
      - ../etc/uwsgi:/etc/uwsgi:ro
      - socket-volume:/tmp/sockets

  webpack_builder:
    image: jnorwood/stupidchess-webpack_builder:current
    entrypoint:
      - node_modules/webpack/bin/webpack.js
      - --watch
      - --devtool
      - source-map
    volumes:
      - ../web/src:/var/lib/johnmalcolmnorwood/stupidchess/src:ro
      - frontend-public-volume:/var/lib/johnmalcolmnorwood/stupidchess/dist
