version: "3"

services:
  console_script:
    image: stupidchess-uwsgi:current
    entrypoint:
      - python
    environment:
      - JCONFIGURE_ACTIVE_PROFILES=LCL
      - JCONFIGURE_CONFIG_DIRECTORIES=/var/lib/johnmalcolmnorwood/stupidchess/server/config
    volumes:
      - ../../server/packages/stupidchess/src/com/johnmalcolmnorwood/stupidchess:/usr/local/lib/python3.6/site-packages/com/johnmalcolmnorwood/stupidchess:ro
      - ../../server/config:/var/lib/johnmalcolmnorwood/stupidchess/server/config:ro

